apiVersion: 1.0.0
metadata:
  generateName: golang-aoc-
projects:
  - name: example
    source:
      location: 'https://github.com/yeungalan0/misc.git'
      type: git
    clonePath: misc
components:
  - id: golang/go/latest
    memoryLimit: 512Mi
    preferences:
      go.lintTool: golangci-lint
      go.useLanguageServer: true
      go.lintFlags: '--fast'
    type: chePlugin
    alias: go-plugin
    env:
      - value: 'off'
        name: GO111MODULE
  - mountSources: true
    memoryLimit: 2Gi
    type: dockerimage
    image: 'quay.io/eclipse/che-golang-1.14:nightly'
    alias: go-cli
    env:
      - value: $(CHE_PROJECTS_ROOT)
        name: GOPATH
      - value: /tmp/.cache
        name: GOCACHE
      - value: $(CHE_PROJECTS_ROOT)/misc/advent_of_code_2020/config
        name: AOC_GO_CONFIG_DIR
commands:
  - name: Run current file
    actions:
      - workdir: '${fileDirname}'
        type: exec
        command: 'go get -d && go run ${file}'
        component: go-cli
  - name: Debug current file
    actions:
      - referenceContent: |
          {
            "version": "0.2.0",
            "configurations": [
              {
                "name": "Debug current file",
                "type": "go",
                "request": "launch",
                "mode": "auto",
                "program": "${fileDirname}"
              }
            ]
          }
        type: vscode-launch
